name: Test PR on Merge

on: pull_request

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-pr-airbnb:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{github.workspace}}/app
    steps:
      - name: Checkout App
        id: checkout
        uses: actions/checkout@v3
      - name: Server | Setup Node and NPM Cache
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: ${{ github.workspace }}/server/package-lock.json
      - name: Install Dependencies
        working-directory: ./server
        run: npm install
      - name: Install Layer Dependencies
        working-directory: ${{ github.workspace }}/server/prisma
        run: PRISMA_CLI_BINARY_TARGETS=rhel-openssl-1.0.x npm i
      - name: Build Distribution
        working-directory: ./server
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm run build
      - name: Test Server
        working-directory: ./server
        run: npm run test
      - name: Download Coverage
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: deploy-to-production.yml
          name: jest-report-main
          path: ${{ github.workspace }}/server/jest-report-main
      - name: Jest Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: ${{ github.workspace }}/server/coverage/report.json
          base-coverage-file: ${{ github.workspace }}/server/jest-report-main/report.json
          annotations: none
